#
#  â–„â–€â–ˆâ€ƒâ–ˆâ–‘â–‘â€ƒâ–ˆâ–„â–€â€ƒâ–„â–€â–ˆâ€ƒâ–ˆâ–€â–€â€ƒâ–ˆâ–€â–„â€ƒâ–„â–€â–ˆâ€ƒâ–„â–€â–ˆâ€ƒâ–ˆâ–‘â–ˆâ€ƒâ–ˆâ–‘â–ˆâ€ƒâ–ˆâ–€â–€â€ƒâ–ˆâ–€â–€
#  â–ˆâ–€â–ˆâ€ƒâ–ˆâ–„â–„â€ƒâ–ˆâ–‘â–ˆâ€ƒâ–ˆâ–€â–ˆâ€ƒâ–ˆâ–ˆâ–„â€ƒâ–ˆâ–„â–€â€ƒâ–ˆâ–€â–ˆâ€ƒâ–ˆâ–€â–ˆâ€ƒâ–€â–„â–€â€ƒâ–ˆâ–€â–ˆâ€ƒâ–ˆâ–„â–„â€ƒâ–ˆâ–€â–‘
#
#               Plugin by nmoralesFZ
#             Discord: nmoralesFZ#2607            
#  DescÃ¡rgalo desde: https://www.nmoralesfz.tk/s/av

server_name: "&l&bTu&fServer" # Soporte para coloreado con & (no uses Â§ o no funcionarÃ¡).
map_number: "1" # SÃ³lo nÃºmeros, sin letras.
URL: "https://discord.com/api/webhooks/" # Ingresa tu webhook para anunciar KOTH's y otras cosas.

# --------------------------------------------------------
# ğŸ¢ƒ MenÃº de kits inicia aquÃ­ ğŸ¢ƒ
kits:
  menu.name: '&l&bKits'
  item.slot.empty: '0:0'
  item.kit.lore:
    - ''
    - '&bTiempo de espera: &7{kit_cooldown}'
    - '&bTu tiempo de espera: &7{player_cooldown}'
    - '&bCompra este kit y mucho mÃ¡s en &l&o&ftienda.tuip.com&r'
# ğŸ¢ MenÃº de kits termina aquÃ­ ğŸ¢ 
# --------------------------------------------------------
# ğŸ¢ƒ ConfiguraciÃ³n de cooldowns (tiempos de espera) inicia aquÃ­ ğŸ¢ƒ
Global:
Cooldowns:
  EnderPearl: 15
  CombatTag: 30
  ArcherTag: 10
  LoggerBait: 30
  Apple: 15
  EggPort: 15
  SpecialItem: 15
  StormBreaker: 120
  Bard: 120
  RogueItem: 15
  Berserk: 120
  NinjaShear: 120
  PotionCounter: 90
  AntiTrapper: 120
  AntiTrapperTarget: 20
  Home: 10
  Stuck: 35
  Logout: 16
# ğŸ¢ ConfiguraciÃ³n de cooldowns (tiempos de espera) termina aquÃ­ ğŸ¢ 
# --------------------------------------------------------
# ğŸ¢ƒ ConfiguraciÃ³n de factions inicia aquÃ­ ğŸ¢ƒ
FactionsConfig:
  maxPlayers: 12
  SpreadWater: true
  BorderLimit: 2000
  Warzone: 300
# ğŸ¢ ConfiguraciÃ³n de factions termina aquÃ­ ğŸ¢ 
# --------------------------------------------------------
# ğŸ¢ƒ ConfiguraciÃ³n de dimensiones inicia aquÃ­ ğŸ¢ƒ
LevelManager:
  EntitySpawnDelay: 400
  levelEndName: "endav"
  levelNetherName: "netherav"
block_ids: ["119:0", "120:0"]
items_id: ["46:0", "259:0, 2257:0"]
# ğŸ¢ ConfiguraciÃ³n de dimensiones termina aquÃ­ ğŸ¢ 
